app/blueprints/blog.py
# -*- coding: utf-8 -*-
'''
@Author: zhou
@Date : 2019/3/18 下午10:05
@Desc :
'''

from flask import Blueprint, render_template, request, current_app

from app.models import Post

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)  # 从查询字符串获取当前页数
    per_page = current_app.config['BLOG_POST_PER_PAGE']  # 每页数量
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items  # 当前页数的记录列表
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    return render_template('blog/category.html')


@blog_bp.route('/post/<slug>', methods=['GET', 'POST'])
def show_post(slug):
    # post = Post.query.get_or_404(post_id)
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('blog/post.html', post=post)

app/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', slug=post.slug) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', slug=post.slug) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post', slug=post.slug) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
    </div>
{% endif %}

app/templates/blog/_sidebar.html
{% if links %}
    <div class="card mb-3">
        <div class="card-header">Links</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if categories %}
    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Change Theme
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.BLOG_THEMES.items() %}
{#            <a class="dropdown-item"#}
{#               href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">#}
{#                {{ display_name }}</a>#}
        {% endfor %}
    </div>
</div>

app/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ admin.about|safe }}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

app/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

app/templates/blog/index.html
{% extends 'base.html' %}
{#{% from 'bootstrap/pagination.html' import render_pager %}#}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

app/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}
            <span class="float-right">
      </span>
        </h1>
        <small>
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a><br>
            Date: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
{#            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">Share#}
{#            </button>#}
            {{ share.create(title='Share with: ',sites='weibo, wechat, qq') }}
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', slug=post.slug, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{#            <div class="comments" id="comments">#}
{#                <h3>{{ comments|length }} Comments#}
{#                    <small>#}
{#                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">#}
{#                            latest</a>#}
{#                    </small>#}
{#                </h3>#}
{#                {% if comments %}#}
{#                    <ul class="list-group">#}
{#                        {% for comment in comments %}#}
{#                            <li class="list-group-item list-group-item-action flex-column">#}
{#                                <div class="d-flex w-100 justify-content-between">#}
{#                                    <h5 class="mb-1">#}
{#                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"#}
{#                                           target="_blank">#}
{#                                            {% if comment.from_admin %}#}
{#                                                {{ admin.name }}#}
{#                                            {% else %}#}
{#                                                {{ comment.author }}#}
{#                                            {% endif %}#}
{#                                        </a>#}
{#                                        {% if comment.from_admin %}#}
{#                                            <span class="badge badge-primary">Author</span>{% endif %}#}
{#                                        {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}#}
{#                                    </h5>#}
{#                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"#}
{#                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">#}
{#                                        {{ moment(comment.timestamp).fromNow() }}#}
{#                                    </small>#}
{#                                </div>#}
{#                                {% if comment.replied %}#}
{#                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}:#}
{#                                        <br>{{ comment.replied.body }}#}
{#                                    </p>#}
{#                                {%- endif -%}#}
{#                                <p class="mb-1">{{ comment.body }}</p>#}
{#                                <div class="float-right">#}
{#                                    <a class="btn btn-light btn-sm"#}
{#                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>#}
{#                                </div>#}
{#                            </li>#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#                {% else %}#}
{#                    <div class="tip"><h5>No comments.</h5></div>#}
{#                {% endif %}#}
{#            </div>#}
{#            {% if comments %}#}
{#                {{ render_pagination(pagination, fragment='#comments') }}#}
{#            {% endif %}#}
{#            {% if request.args.get('reply') %}#}
{#                <div class="alert alert-dark">#}
{#                    Reply to <strong>{{ request.args.get('author') }}</strong>:#}
{#                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>#}
{#                </div>#}
{#            {% endif %}#}
{#            <div id="comment-form">#}
{#                {{ render_form(form, action=request.full_path) }}#}
{#            </div>#}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}